version: 2.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: nuget restore StreamGoo.sln
build:
  project: StreamGoo.csproj
  verbosity: minimal
after_build:
- pwsh: >-
    dotnet publish StreamGoo.csproj /p:PublishProfile=FolderProfileWinx64

    dotnet publish StreamGoo.csproj /p:PublishProfile=FolderProfileLinx64
    
    7z a StreamGoo-Win-x64-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_VERSION-Bulk.zip $Env:APPVEYOR_BUILD_FOLDER
    
    appveyor PushArtifact StreamGoo-Win-x64-$Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_VERSION-Bulk.zip

    appveyor PushArtifact $Env:APPVEYOR_BUILD_FOLDER\bin\Release\net6.0\publish\win-x64\StreamGoo.exe
        
    appveyor PushArtifact $Env:APPVEYOR_BUILD_FOLDER\bin\Release\net6.0\publish\linux-x64\StreamGoo